include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore    # suppresses Freezed annotation noise
  exclude:
    - build/**
    - android/**
    - ios/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - use_super_parameters
    - prefer_final_locals
    - avoid_redundant_argument_values
